# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: API Use Cases
author: Scott Brandenberg, Meera Kota

nav:
    - Home: api_background.ipynb
    
plugins:
    - mkdocs-jupyter
